export interface Country { name: string; native: string; flag: string; }

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', native: 'افغانستان', flag: '🇦🇫' },
  { name: 'Albania', native: 'Shqipëri', flag: '🇦🇱' },
  { name: 'Algeria', native: 'الجزائر', flag: '🇩🇿' },
  { name: 'Andorra', native: 'Andorra', flag: '🇦🇩' },
  { name: 'Angola', native: 'Angola', flag: '🇦🇴' },
  { name: 'Antigua and Barbuda', native: 'Antigua and Barbuda', flag: '🇦🇬' },
  { name: 'Argentina', native: 'Argentina', flag: '🇦🇷' },
  { name: 'Armenia', native: 'Հայաստան', flag: '🇦🇲' },
  { name: 'Australia', native: 'Australia', flag: '🇦🇺' },
  { name: 'Austria', native: 'Österreich', flag: '🇦🇹' },
  { name: 'Azerbaijan', native: 'Azərbaycan', flag: '🇦🇿' },
  { name: 'Bahamas', native: 'Bahamas', flag: '🇧🇸' },
  { name: 'Bahrain', native: 'البحرين', flag: '🇧🇭' },
  { name: 'Bangladesh', native: 'বাংলাদেশ', flag: '🇧🇩' },
  { name: 'Barbados', native: 'Barbados', flag: '🇧🇧' },
  { name: 'Belarus', native: 'Беларусь', flag: '🇧🇾' },
  { name: 'Belgium', native: 'België', flag: '🇧🇪' },
  { name: 'Belize', native: 'Belize', flag: '🇧🇿' },
  { name: 'Benin', native: 'Bénin', flag: '🇧🇯' },
  { name: 'Bhutan', native: 'འབྲུག', flag: '🇧🇹' },
  { name: 'Bolivia', native: 'Bolivia', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', native: 'Bosna i Hercegovina', flag: '🇧🇦' },
  { name: 'Botswana', native: 'Botswana', flag: '🇧🇼' },
  { name: 'Brazil', native: 'Brasil', flag: '🇧🇷' },
  { name: 'Brunei', native: 'Brunei', flag: '🇧🇳' },
  { name: 'Bulgaria', native: 'България', flag: '🇧🇬' },
  { name: 'Burkina Faso', native: 'Burkina Faso', flag: '🇧🇫' },
  { name: 'Burundi', native: 'Burundi', flag: '🇧🇮' },
  { name: 'Cabo Verde', native: 'Cabo Verde', flag: '🇨🇻' },
  { name: 'Cambodia', native: 'កម្ពុជា', flag: '🇰🇭' },
  { name: 'Cameroon', native: 'Cameroun', flag: '🇨🇲' },
  { name: 'Canada', native: 'Canada', flag: '🇨🇦' },
  { name: 'Central African Republic', native: 'Ködörösêse tî Bêafrîka', flag: '🇨🇫' },
  { name: 'Chad', native: 'تشاد', flag: '🇹🇩' },
  { name: 'Chile', native: 'Chile', flag: '🇨🇱' },
  { name: 'China', native: '中国', flag: '🇨🇳' },
  { name: 'Colombia', native: 'Colombia', flag: '🇨🇴' },
  { name: 'Comoros', native: 'جزر القمر', flag: '🇰🇲' },
  { name: 'Congo', native: 'Congo', flag: '🇨🇬' },
  { name: 'Costa Rica', native: 'Costa Rica', flag: '🇨🇷' },
  { name: 'Croatia', native: 'Hrvatska', flag: '🇭🇷' },
  { name: 'Cuba', native: 'Cuba', flag: '🇨🇺' },
  { name: 'Cyprus', native: 'Κύπρος', flag: '🇨🇾' },
  { name: 'Czech Republic', native: 'Česká republika', flag: '🇨🇿' },
  { name: 'Denmark', native: 'Danmark', flag: '🇩🇰' },
  { name: 'Djibouti', native: 'جيبوتي', flag: '🇩🇯' },
  { name: 'Dominica', native: 'Dominica', flag: '🇩🇲' },
  { name: 'Dominican Republic', native: 'República Dominicana', flag: '🇩🇴' },
  { name: 'DR Congo', native: 'République démocratique du Congo', flag: '🇨🇩' },
  { name: 'Ecuador', native: 'Ecuador', flag: '🇪🇨' },
  { name: 'Egypt', native: 'مصر', flag: '🇪🇬' },
  { name: 'El Salvador', native: 'El Salvador', flag: '🇸🇻' },
  { name: 'Equatorial Guinea', native: 'Guinea Ecuatorial', flag: '🇬🇶' },
  { name: 'Eritrea', native: 'ኤርትራ', flag: '🇪🇷' },
  { name: 'Estonia', native: 'Eesti', flag: '🇪🇪' },
  { name: 'Eswatini', native: 'eSwatini', flag: '🇸🇿' },
  { name: 'Ethiopia', native: 'ኢትዮጵያ', flag: '🇪🇹' },
  { name: 'Fiji', native: 'Fiji', flag: '🇫🇯' },
  { name: 'Finland', native: 'Suomi', flag: '🇫🇮' },
  { name: 'France', native: 'France', flag: '🇫🇷' },
  { name: 'Gabon', native: 'Gabon', flag: '🇬🇦' },
  { name: 'Gambia', native: 'Gambia', flag: '🇬🇲' },
  { name: 'Georgia', native: 'საქართველო', flag: '🇬🇪' },
  { name: 'Germany', native: 'Deutschland', flag: '🇩🇪' },
  { name: 'Ghana', native: 'Ghana', flag: '🇬🇭' },
  { name: 'Greece', native: 'Ελλάδα', flag: '🇬🇷' },
  { name: 'Grenada', native: 'Grenada', flag: '🇬🇩' },
  { name: 'Guatemala', native: 'Guatemala', flag: '🇬🇹' },
  { name: 'Guinea', native: 'Guinée', flag: '🇬🇳' },
  { name: 'Guinea-Bissau', native: 'Guiné-Bissau', flag: '🇬🇼' },
  { name: 'Guyana', native: 'Guyana', flag: '🇬🇾' },
  { name: 'Haiti', native: 'Haïti', flag: '🇭🇹' },
  { name: 'Honduras', native: 'Honduras', flag: '🇭🇳' },
  { name: 'Hungary', native: 'Magyarország', flag: '🇭🇺' },
  { name: 'Iceland', native: 'Ísland', flag: '🇮🇸' },
  { name: 'India', native: 'भारत', flag: '🇮🇳' },
  { name: 'Indonesia', native: 'Indonesia', flag: '🇮🇩' },
  { name: 'Iran', native: 'ایران', flag: '🇮🇷' },
  { name: 'Iraq', native: 'العراق', flag: '🇮🇶' },
  { name: 'Ireland', native: 'Éire', flag: '🇮🇪' },
  { name: 'Israel', native: 'ישראל', flag: '🇮🇱' },
  { name: 'Italy', native: 'Italia', flag: '🇮🇹' },
  { name: 'Ivory Coast', native: "Côte d'Ivoire", flag: '🇨🇮' },
  { name: 'Jamaica', native: 'Jamaica', flag: '🇯🇲' },
  { name: 'Japan', native: '日本', flag: '🇯🇵' },
  { name: 'Jordan', native: 'الأردن', flag: '🇯🇴' },
  { name: 'Kazakhstan', native: 'Қазақстан', flag: '🇰🇿' },
  { name: 'Kenya', native: 'Kenya', flag: '🇰🇪' },
  { name: 'Kiribati', native: 'Kiribati', flag: '🇰🇮' },
  { name: 'Kosovo', native: 'Kosovë', flag: '🇽🇰' },
  { name: 'Kuwait', native: 'الكويت', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', native: 'Кыргызстан', flag: '🇰🇬' },
  { name: 'Laos', native: 'ລາວ', flag: '🇱🇦' },
  { name: 'Latvia', native: 'Latvija', flag: '🇱🇻' },
  { name: 'Lebanon', native: 'لبنان', flag: '🇱🇧' },
  { name: 'Lesotho', native: 'Lesotho', flag: '🇱🇸' },
  { name: 'Liberia', native: 'Liberia', flag: '🇱🇷' },
  { name: 'Libya', native: 'ليبيا', flag: '🇱🇾' },
  { name: 'Liechtenstein', native: 'Liechtenstein', flag: '🇱🇮' },
  { name: 'Lithuania', native: 'Lietuva', flag: '🇱🇹' },
  { name: 'Luxembourg', native: 'Lëtzebuerg', flag: '🇱🇺' },
  { name: 'Madagascar', native: 'Madagasikara', flag: '🇲🇬' },
  { name: 'Malawi', native: 'Malawi', flag: '🇲🇼' },
  { name: 'Malaysia', native: 'Malaysia', flag: '🇲🇾' },
  { name: 'Maldives', native: 'ދިވެހިރާއްޖެ', flag: '🇲🇻' },
  { name: 'Mali', native: 'Mali', flag: '🇲🇱' },
  { name: 'Malta', native: 'Malta', flag: '🇲🇹' },
  { name: 'Marshall Islands', native: 'Marshall Islands', flag: '🇲🇭' },
  { name: 'Mauritania', native: 'موريتانيا', flag: '🇲🇷' },
  { name: 'Mauritius', native: 'Maurice', flag: '🇲🇺' },
  { name: 'Mexico', native: 'México', flag: '🇲🇽' },
  { name: 'Micronesia', native: 'Micronesia', flag: '🇫🇲' },
  { name: 'Moldova', native: 'Moldova', flag: '🇲🇩' },
  { name: 'Monaco', native: 'Monaco', flag: '🇲🇨' },
  { name: 'Mongolia', native: 'Монгол', flag: '🇲🇳' },
  { name: 'Montenegro', native: 'Crna Gora', flag: '🇲🇪' },
  { name: 'Morocco', native: 'المغرب', flag: '🇲🇦' },
  { name: 'Mozambique', native: 'Moçambique', flag: '🇲🇿' },
  { name: 'Myanmar', native: 'မြန်မာ', flag: '🇲🇲' },
  { name: 'Namibia', native: 'Namibia', flag: '🇳🇦' },
  { name: 'Nauru', native: 'Nauru', flag: '🇳🇷' },
  { name: 'Nepal', native: 'नेपाल', flag: '🇳🇵' },
  { name: 'Netherlands', native: 'Nederland', flag: '🇳🇱' },
  { name: 'New Zealand', native: 'Aotearoa', flag: '🇳🇿' },
  { name: 'Nicaragua', native: 'Nicaragua', flag: '🇳🇮' },
  { name: 'Niger', native: 'Niger', flag: '🇳🇪' },
  { name: 'Nigeria', native: 'Nigeria', flag: '🇳🇬' },
  { name: 'North Korea', native: '조선민주주의인민공화국', flag: '🇰🇵' },
  { name: 'North Macedonia', native: 'Северна Македонија', flag: '🇲🇰' },
  { name: 'Norway', native: 'Norge', flag: '🇳🇴' },
  { name: 'Oman', native: 'عُمان', flag: '🇴🇲' },
  { name: 'Pakistan', native: 'پاکستان', flag: '🇵🇰' },
  { name: 'Palau', native: 'Palau', flag: '🇵🇼' },
  { name: 'Palestine', native: 'فلسطين', flag: '🇵🇸' },
  { name: 'Panama', native: 'Panamá', flag: '🇵🇦' },
  { name: 'Papua New Guinea', native: 'Papua New Guinea', flag: '🇵🇬' },
  { name: 'Paraguay', native: 'Paraguay', flag: '🇵🇾' },
  { name: 'Peru', native: 'Perú', flag: '🇵🇪' },
  { name: 'Philippines', native: 'Pilipinas', flag: '🇵🇭' },
  { name: 'Poland', native: 'Polska', flag: '🇵🇱' },
  { name: 'Portugal', native: 'Portugal', flag: '🇵🇹' },
  { name: 'Qatar', native: 'قطر', flag: '🇶🇦' },
  { name: 'Romania', native: 'România', flag: '🇷🇴' },
  { name: 'Russia', native: 'Россия', flag: '🇷🇺' },
  { name: 'Rwanda', native: 'Rwanda', flag: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', native: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { name: 'Saint Lucia', native: 'Saint Lucia', flag: '🇱🇨' },
  { name: 'Saint Vincent and the Grenadines', native: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { name: 'Samoa', native: 'Sāmoa', flag: '🇼🇸' },
  { name: 'San Marino', native: 'San Marino', flag: '🇸🇲' },
  { name: 'São Tomé and Príncipe', native: 'São Tomé e Príncipe', flag: '🇸🇹' },
  { name: 'Saudi Arabia', native: 'المملكة العربية السعودية', flag: '🇸🇦' },
  { name: 'Senegal', native: 'Sénégal', flag: '🇸🇳' },
  { name: 'Serbia', native: 'Srbija', flag: '🇷🇸' },
  { name: 'Seychelles', native: 'Seychelles', flag: '🇸🇨' },
  { name: 'Sierra Leone', native: 'Sierra Leone', flag: '🇸🇱' },
  { name: 'Singapore', native: 'Singapore', flag: '🇸🇬' },
  { name: 'Slovakia', native: 'Slovensko', flag: '🇸🇰' },
  { name: 'Slovenia', native: 'Slovenija', flag: '🇸🇮' },
  { name: 'Solomon Islands', native: 'Solomon Islands', flag: '🇸🇧' },
  { name: 'Somalia', native: 'Soomaaliya', flag: '🇸🇴' },
  { name: 'South Africa', native: 'South Africa', flag: '🇿🇦' },
  { name: 'South Korea', native: '대한민국', flag: '🇰🇷' },
  { name: 'South Sudan', native: 'South Sudan', flag: '🇸🇸' },
  { name: 'Spain', native: 'España', flag: '🇪🇸' },
  { name: 'Sri Lanka', native: 'ශ්‍රී ලංකාව', flag: '🇱🇰' },
  { name: 'Sudan', native: 'السودان', flag: '🇸🇩' },
  { name: 'Suriname', native: 'Suriname', flag: '🇸🇷' },
  { name: 'Sweden', native: 'Sverige', flag: '🇸🇪' },
  { name: 'Switzerland', native: 'Schweiz', flag: '🇨🇭' },
  { name: 'Syria', native: 'سوريا', flag: '🇸🇾' },
  { name: 'Taiwan', native: '台灣', flag: '🇹🇼' },
  { name: 'Tajikistan', native: 'Тоҷикистон', flag: '🇹🇯' },
  { name: 'Tanzania', native: 'Tanzania', flag: '🇹🇿' },
  { name: 'Thailand', native: 'ประเทศไทย', flag: '🇹🇭' },
  { name: 'Timor-Leste', native: 'Timor-Leste', flag: '🇹🇱' },
  { name: 'Togo', native: 'Togo', flag: '🇹🇬' },
  { name: 'Tonga', native: 'Tonga', flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', native: 'Trinidad and Tobago', flag: '🇹🇹' },
  { name: 'Tunisia', native: 'تونس', flag: '🇹🇳' },
  { name: 'Turkey', native: 'Türkiye', flag: '🇹🇷' },
  { name: 'Turkmenistan', native: 'Türkmenistan', flag: '🇹🇲' },
  { name: 'Tuvalu', native: 'Tuvalu', flag: '🇹🇻' },
  { name: 'UAE', native: 'الإمارات', flag: '🇦🇪' },
  { name: 'Uganda', native: 'Uganda', flag: '🇺🇬' },
  { name: 'Ukraine', native: 'Україна', flag: '🇺🇦' },
  { name: 'United Kingdom', native: 'United Kingdom', flag: '🇬🇧' },
  { name: 'United States', native: 'United States', flag: '🇺🇸' },
  { name: 'Uruguay', native: 'Uruguay', flag: '🇺🇾' },
  { name: 'Uzbekistan', native: "O'zbekiston", flag: '🇺🇿' },
  { name: 'Vanuatu', native: 'Vanuatu', flag: '🇻🇺' },
  { name: 'Vatican City', native: 'Città del Vaticano', flag: '🇻🇦' },
  { name: 'Venezuela', native: 'Venezuela', flag: '🇻🇪' },
  { name: 'Vietnam', native: 'Việt Nam', flag: '🇻🇳' },
  { name: 'Yemen', native: 'اليمن', flag: '🇾🇪' },
  { name: 'Zambia', native: 'Zambia', flag: '🇿🇲' },
  { name: 'Zimbabwe', native: 'Zimbabwe', flag: '🇿🇼' },
];

export function countryFlag(name: string): string {
  return COUNTRIES.find(c => c.name === name)?.flag ?? '🌍';
}
